doc/en/html/about/history.html
doc/ja/html/about/history.html
teraterm/teraterm/ttdde.c

- 送信終了時に EndDdeCmnd(0) をコールするよう修正
- #19

TTL Script fails at 'sendfile'

---

cygwin/cyglaunch/cyglaunch.v17.vcxproj
teraterm/keycode/keycode.v17.vcxproj
teraterm/teraterm/ttermpro.v17.vcxproj
teraterm/ttpcmn/ttpcmn.v17.vcxproj
teraterm/ttpmacro/ttpmacro.v17.vcxproj
teraterm/ttptek/ttptek.v17.vcxproj

- VS2019のプロジェクトファイルに依存していた
- VS2022でビルドする時に2019(v142ビルドツール)をインストールしている必要があった

VS2022のプロジェクトファイルの参照誤りを修正

---

doc/en/html/about/history.html
doc/ja/html/about/history.html
ttpmenu/readme.txt
ttpmenu/ttpmenu-version.h
ttpmenu/ttpmenu.cpp

- 接続先が登録されていないとき、"(none)"が表示されるよう修正した。
- "(" が表示されていた
- readme.txtに更新履歴を追記
- 改版履歴追記
- バージョン更新
- 1.18 -> 1.19

接続先が登録されていないとき、"(none)"が表示されるよう修正 #76

---

teraterm/common/compat_win.cpp
teraterm/teraterm/vtdisp.c

- TransparentBlt API を使用できるよう修正
- 文字描画時にフォントサイズが1pixel大きい場合、縮小せずに描画するようにした

文字が透過しない場合があったので修正

---

TTXSamples/TTXKcodeChange/.editorconfig
TTXSamples/TTXKcodeChange/ReadMe-ja.txt
TTXSamples/TTXKcodeChange/TTXKcodeChange.c
doc/en/html/about/history.html
doc/en/html/commandline/teraterm.html
doc/en/html/macro/command/callmenu.html
doc/en/html/menu/setup-terminal_ko.html
doc/en/html/menu/setup-terminal_utf8.html
doc/en/html/reference/menu_id.html
doc/ja/html/about/history.html
doc/ja/html/commandline/teraterm.html
doc/ja/html/macro/command/callmenu.html
doc/ja/html/menu/setup-terminal_ko.html
doc/ja/html/menu/setup-terminal_utf8.html
doc/ja/html/reference/menu_id.html
doc/ja/html/usage/kcodechange.html
installer/release/lang_utf8/Spanish.lng
teraterm/ttpset/ttset.c

- Tera Term 4 に存在していた文字コード
- Tera Term 5 では UTF-8 と UTF-8m を分ける必要がなくなった
- 5ed92d3 (r9528) でコマンドラインオプション /KR,/KT に UTF8m が指定されると UTF8 と同等としていた

UTF-8m, UTF8m を削除 #63

---

teraterm/teraterm/tt-version.rc

- a069aba で長くした
- タスクマネージャーのプロセス名に使用される
- 見にくくなるので元に戻す

ttermpro.exe の FileDescription が長いので元に戻す #119

---

doc/en/html/about/history.html
doc/en/html/macro/commandline.html
doc/ja/html/about/history.html
doc/ja/html/macro/commandline.html
teraterm/ttpmacro/ttl.cpp
teraterm/ttpmacro/ttmdlg.cpp
teraterm/ttpmacro/ttmdlg.h
teraterm/ttpmacro/ttmmain.cpp

- ttpmacroにTTLファイルを相対パスで指定したとき、ttpmacroのカレントディレクトリ相対で扱うようにした
- コマンドライン(シェル)から起動したときの動作が自然になった
- 変更前は、読み込む TERATERM.INI のあるフォルダ相対で扱っていた
- マニュアルを修正

ttpmacro の TTLファイル指定の扱いを変更した #127

---

doc/en/html/about/history.html
doc/ja/html/about/history.html
ttssh2/ttxssh/auth.c
ttssh2/ttxssh/keyfiles.c
ttssh2/ttxssh/keyfiles.h
ttssh2/ttxssh/ttxssh.c
ttssh2/ttxssh/ttxssh.h

- 変更前はACPだった
- `"id_rsa😄"` などもokとなる

ttxsshの鍵ファイル名にUnicodeを使用できるようにする

---

doc/en/html/about/glossary.html
doc/en/html/about/history.html
doc/en/html/menu/setup-additional-coding.html
doc/ja/html/about/glossary.html
doc/ja/html/about/history.html
doc/ja/html/menu/setup-additional-coding.html
teraterm/teraterm/unicode/get_emoji_table.pl
teraterm/teraterm/unicode_emoji.tbl
tests/unicodebuf-text-emoji.txt

絵文字テーブルを変更します。
テストしていて2cellのほうが自然そうだけど、
Override Emoji Characters width = 2にしても
1cellで表示される文字を見つけました。
例
☇:U+2607 LIGHTNING
☻:U+263B BLACK SMILING FACE
webブラウザでの文字の見え方は選択したフォントによると思います。
Tera Term上などで次のコマンドで見え方をチェックできます。
```
wget https://raw.githubusercontent.com/TeraTermProject/teraterm/emoji_width/tests/unicodebuf-text-emoji.txt -O -
```
絵文字の種類(=属性, Properties)が6種あって、
https://www.unicode.org/reports/tr51/#Emoji_Properties_and_Data_Files
現在はEmoji属性の文字を絵文字としています。
これよりもExtended_Pictographic属性を使ったほうがよさそうです。
それなら上記文字も2cellで表示することがでるようになります。
Unicodeにしかない(Shift_JIS(CP932) などにはない)絵文字の
文字幅はどうしたものかなと思うのですが
2cell(全角)のほうが違和感がない印象です。
将来絵文字属性によって文字幅を変えたい、となるかもしれないですね。
Unicodeの文字幅の説明にも手を入れました。
特に指摘などなさそうでしたら2,3日でマージしようと思います。

絵文字テーブルを変更

---

teraterm/teraterm/vtwin.cpp

- 初期化されない不定な変数があり、終了時 free() しようとして不正な処理が発生
- #160 と現象は同様なため改修履歴は省略
- 6491bf2

/V オプション指定時、不正な処理で終了しないよう修正 #191

---

doc/en/html/about/history.html
doc/en/html/macro/command/dirname.html
doc/ja/html/about/history.html
doc/ja/html/macro/command/dirname.html
teraterm/common/codeconv.cpp
teraterm/ttpmacro/ttl.cpp

- 修正前はANSI文字列として扱っていた
- ファイル名の取り扱い部分の文字長制限をなくした
- MAX_PATH など文字長定数を使用しない
- _splitpath_s() を使用をやめた
- codeconv.cpp の _MultiByteToWideChar() で変換できない文字が入力された場合の動作を変更
- 従来は変換エラーとなり、NULLを返していた
- 変更後 U+FFFD に置換、または、その文字を削除
- ToCharU8(), ToWcharA(), ToWcharU8(), ToU8A() も影響を受ける
- U+FFFD replacement character
- 不明な文字、認識できない文字、表現できない文字を置き換えるために使用される

basename, dirname で文字列をUnicodeとして扱うようにした #217

---

doc/en/html/about/history.html
doc/en/html/macro/command/index.html
doc/en/html/macro/command/send.html
doc/en/html/macro/command/sendbinary.html
doc/en/html/macro/command/sendtext.html
doc/en/teraterm.hhc
doc/ja/html/about/history.html
doc/ja/html/macro/command/index.html
doc/ja/html/macro/command/send.html
doc/ja/html/macro/command/sendbinary.html
doc/ja/html/macro/command/sendtext.html
doc/ja/html/reference/dev/macro_proto.md
doc/ja/teraterm.hhc
teraterm/common/CMakeLists.txt
teraterm/common/common_static.v16.vcxproj
teraterm/common/common_static.v17.vcxproj
teraterm/common/ddelib.cpp
teraterm/common/ddelib.h
teraterm/common/ttddecmnd.h
teraterm/teraterm/ttdde.c
teraterm/ttpmacro/ttl.cpp
teraterm/ttpmacro/ttmdde.c
teraterm/ttpmacro/ttmparse.cpp
teraterm/ttpmacro/ttmparse.h

- 'send $ff $ff $ff' と送信すると 0x3F 0x3F 0x3F("???") が出力される
- 内部文字コードUTF-16に変換する時、L"???" (変換できない文字3キャラクタ) と変換されるため
- send コマンドで送信したデータがテキストデータなのかバイナリデータなのか判定を誤っていた
- sendマクロコマンドで送信したデータの判定方法を変更
- 従来の方法(#189)に加えて - コントロールコード(改行コード以外の0x20未満のデータ)が入っているか?
- UTF-8 を UTF-16 へ変換、再度UTF-8 へ変換して比較、異なっている場合はバイナリと判定
- sendtext, sendbinary マクロコマンドを追加
- 送信データの自動判定を行わずに送信できる
- XTYP_EXECUTE を使って文字/バイナリを送信するようにした
- 通信データ上限をなくした
- XTYP_POKE は使用しなくなった

sendマクロコマンドで送信したデータが異なったものにならないよう修正 #215

---

teraterm/teraterm/setupdirdlg.cpp

- 単純にフォルダを開くとき, ShellExecuteW() の "explore" + フォルダ で開くようにした
- ShellExecuteW() で explorer.exe を使用するときはフルパスで指定するよう修正

ShellExecuteW() の使い方を見直した #232

---

doc/en/html/about/history.html
doc/ja/html/about/history.html
teraterm/ttpdlg/hostdlg.c
ttssh2/ttxssh/ttxssh.c

- 前回使用した(指定された)comポートを選択した状態でダイアログがオープンするようにした
- Tera Term 4 と同じ動作となった
- 新しい接続ダイアログオープン時comポートが選択されているとフォーカスがおかしくなっていたので修正

新しい接続ダイアログで常にcomポートリストの一番最初が選択されていたので修正 #256

---

doc/en/html/menu/setup-additional-copy-and-paste.html

- Disabling text selection when the window is activated
→ Enabling text selection when the window is activated by mouse

項目名の誤りを修正 #244

---

installer/release/lang_utf8/Japanese.lng
ttssh2/ttxssh/auth.c
ttssh2/ttxssh/auth.h
ttssh2/ttxssh/ssh.c
ttssh2/ttxssh/ttxssh.c

- Tera Termは、Google Authenticator PAMモジュールなどによる二要素認証(TOTPなど)に対応していない
- PuTTYやOpenSSHでは二要素認証が利用できるので、Tera Termでも対応したい
- 追加の認証情報の要求に対応しました
- SSHサーバにGoogle AuthenticatorのPAMモジュールを組み込んでTOTPによる二要素認証などに対応します
- 追加認証を要する場合には、autologinは無効になります（セッション複製時も含む）
- 追加認証を求められたときの日本語メッセージを追加しました
- SSHの接続で、SSH_MSG_USERAUTH_FAILURE に一部成功(partial success)フラグが含まれるとき、追加の認証を求めるダイアログに遷移します
- 一部成功フラグが含まれる場合は追加の認証情報の入力が必要となるため、自動ログイン(autologin)が無効になります
- セッションの複製に使用するため、一部成功の有無と初回の認証メソッドを保持する構造体変数を追加しました
- PR元コミットのコメントに記載しました。
- https://github.com/yasu-hide/teratermproject_teraterm/commit/9e72cc0968f49ffd0315b3a7dbd214861db9413b#commitcomment-140706183

追加の認証情報が必要なSSHログインに対応した

---

teraterm/ttpdlg/generaldlg.c

Setup - General で表示される LanguageUI のドロップダウンリストの内容が二倍になってしまう現象の回避案です。

skip LangAppendFileList when ExeDir is same as HomeDir on General Dlg.

---

ttssh2/ttxssh/auth.c

- 無効な認証方式のラジオボタンにフォーカスが行くことがないようにした
- 4c337af92fd91de6d6cff43014504aaeac6a2fbc と同じ対処
- 4c337af92fd91de6d6cff43014504aaeac6a2fbc での IDCANCEL を IDOK に変更
- コメントを整理
- 378fe5acf6363d6e35424dcda29494bb9f026332 でコードと対応しなくなったコメントを削除

認証ダイアログでフォーカスがなくなることがある問題を修正した #99

---

TTXKanjiMenu/ttxkanjimenu.c

#301 TERATERM.INI で Language=Japanese 又は Korean 以外を指定した場合に、TTXKanjiMenuでACCESS_VIOLATIONが発生する不具合の対応案になります。

TTXKanjiMenuのACCESS_VIOLATION #301

---

TTXKanjiMenu/ttxkanjimenu.rc
doc/en/html/about/history.html
doc/ja/html/about/history.html

TTXKanjiMenu のバージョンを更新、修正履歴に追記 #274

---

doc/en/html/about/history.html
doc/ja/html/about/history.html
teraterm/teraterm/ftdlg.cpp

ESCキー押下時もアイコンを解除するようにした。
×ボタンを押したときにアイコン解除しかしなくなっていたが、ESCキー押下と同じ動き（4.x 相当の動作）に戻した。

get the x button back to work on Tera Term Log dialog

---

teraterm/ttpmacro/ttmmain.cpp

issue #346 のPRになります
teraterm/ttpmacro/ttmmain.cpp CCtrlWindow::OnDpiChanged()の第2引数の脱字の修正
修正前：LRESULT CCtrlWindow::OnDpiChanged(WPARAM wp, LPARAM)
修正後：LRESULT CCtrlWindow::OnDpiChanged(WPARAM wp, LPARAM lp)
- lpは使用していないため実害はありません。
- ユーザへの影響がないため、変更履歴への記載は行いません。

MACRO: CCtrlWindow::OnDpiChanged()の引数の脱字を修正 #346

---

doc/en/html/about/history.html
doc/ja/html/about/history.html
teraterm/common/compat_win.cpp
teraterm/common/compat_win.h
teraterm/common/comportinfo.cpp
teraterm/common/comportinfo.h
teraterm/common/win32helper.cpp
teraterm/common/win32helper.h

- com0com = virtual serial port driver
- シリアルポート、モデムデバイス、に加えて com0com のデバイスもオープンできるようになった
- ただし "CNCA0" などのデバイス名はオープンできない
- comportinfo.cpp を修正
- 全デバイスから必要なデバイスを探すようにした
- 従来OSに対応するためのコードを外部に移動した
- compat_win.cpp,h
- win32helper.cpp,h

com0com の "COM%d" デバイスをオープンできるようにした #365

---

doc/en/html/about/history.html
doc/ja/html/about/history.html
teraterm/ttpmacro/ttl.cpp

マクロコマンド getenv, expandenv, setenv が Unicode に対応していなかったので修正した

getenvにより環境変数定義を取得した際に、日本語を含んでいると文字化けする #388

---

doc/en/html/about/history.html
doc/en/html/usage/mouse.html
doc/ja/html/about/history.html
doc/ja/html/usage/mouse.html
teraterm/teraterm/sendmem.cpp
teraterm/teraterm/sendmem.h
teraterm/teraterm/ttdde.c
teraterm/teraterm/vtwin.cpp

- "Tera Term 4 と同じ方法で送信"=OFF 時
- Terminal tab - Local echo の設定
- file - send file... はローカルエコー設定を反映するようにした
- "Tera Term 4 と同じ方法で送信" は反映するようになっていた
- 次のファイル送信も local echo 設定を反映するようにした
- sendfile マクロコマンド
- Drag and Drop でのファイルの内容送信

Send file 時 local echo 設定を反映するよう修正 #393

---

doc/en/html/about/history.html
doc/ja/html/about/history.html
teraterm/ttpmacro/ttl.cpp

- Write(Get)PrivateProfileStringW() API を使用するようにした
- 修正前は Write(Get)PrivateProfileStringA() API を使用していた

マクロコマンド setpassword, ispassword を Unicode 対応に修正 #422

---

teraterm/ttpfile/zmodem.c

If the receiver does not set CANFDX, then the sender should wait for the receiver to send ZACK for each data subpacket before sending more data.
This allows ZMODEM to be used with a small embedded device that needs ZMODEM to pause while it writes to Flash memory.

ZMODEM send: Disable window if receiver does not set CANFDX flag

---

doc/en/html/about/history.html
doc/ja/html/about/history.html
teraterm/ttpfile/xmodem.c

- XMODEM(CRC)で開始(Cを受信)した後、最初のパケットの応答がNAKの時、 XMODEM(checksum)に切り替わらないようにした
- 最初のパケットの応答のNAKで、XMODEM(checksum)に切り替わっていた。

XMODEM SEND時、送信方法が途中で切り替わらないようにした #428

---

doc/en/html/about/history.html
doc/ja/html/about/history.html
teraterm/teraterm/externalsetup.cpp
teraterm/teraterm/font_pp.cpp
teraterm/teraterm/vtdisp.c
teraterm/teraterm/vtdisp.h
teraterm/teraterm/vtwin.cpp

- Windows11 24H2 で発生
- DPIが異なるディスプレイをまたいでウィンドウを移動したとき、WM_DPICHANGED が送られてくる。 この時ウィンドウの表示されているディスプレイを調べると、またぐ前のディスプレイを返してくるため 誤ったDPIを元にフォントのサイズを決定していた
- WM_DPICHANGED メッセージと一緒に受け取る DPI は、またいだ後のディスプレイのDPIのようなので これを使ってフォントサイズを決定するようにした

正しいDPIが取得できない場合でも動作するよう修正 #449

---

ttssh2/libsshagentc/sshagentc/sshagentc.v16.vcxproj
ttssh2/libsshagentc/sshagentc/sshagentc.v17.vcxproj

- プログラム全体の最適化をオフ
- x64プラットフォームを削除
MSIL .netmodule または /GL を伴ってコンパイルされたモジュールが見つかりました。 /LTCG を使用して再開始してください。リンカーのパフォーマンスを向上させるためには、
コマンドラインに /LTCG を追加してください。
MSIL .netmodule or module compiled with /GL found; restarting link with /LTCG;
add /LTCG to the link command line to improve linker performance
変更履歴 不要
port 不要

リンク時に警告が出ないようオプションを修正 #445

---

teraterm/teraterm/filesys_proto.cpp

- キャンセルボタン押下後、
- CAN(0x18) x 8 + 0x08 x 10 を送信する処理を行うようにした
- 従来は処理が打ち切られて送信されていなかった

ZMODEMの送信キャンセル時、処理が打ち切られないようにした

---

buildtools/install_sbapplocale.bat
buildtools/install_sbapplocale.cmake
buildtools/install_sbapplocale.md
doc/makechm.bat

- ヘルプコンパイラ(hhc.exe)の動作はOSの設定で変わるらしい
- 英語Windows(非日本語Windows)で日本語ヘルプを作成すると文字化けが発生する
- 動作環境を調整するSBAppLocaleの上でhhcを動かして文字化けを回避する

chmファイルの文字化けを修正 #475

---

ci_scripts/build_appveyor_release_bat.bat
installer/makearchive.bat
installer/release.bat
teraterm/teraterm/log_pp.cpp

ビルドエラー発生時に GitHub Actions でエラーにならないのを修正
6febb9bc15b60c0dfc3e395cf9c0c13b77595b0e のコミットを入れて、意図的にビルドを失敗されたもの
ビルドに失敗しているけど、Actions 上でエラーになっていない。
https://github.com/m-tmatma/teraterm/actions/runs/13731158644
バッチファイルでエラーを返して、呼び出し元でエラーを返して、GitHub Actions 上でエラーと認識されるようにしたもの
https://github.com/m-tmatma/teraterm/actions/runs/13731170930
47d1e6f9cc3d5bdee57d79f86a85ed8aa1e45940 で 6febb9bc15b60c0dfc3e395cf9c0c13b77595b0e を revert して、意図的なエラーを解消したもの
https://github.com/m-tmatma/teraterm/actions/runs/13731176105

ビルドエラー発生時に GitHub Actions でエラーにならないのを修正

---

README.md

CI の状態を確認できるように badge を追加する
こんな感じの表示になります。
https://github.com/m-tmatma/teraterm/tree/feature/add-badge
Badge はリンクになっていて、クリックすると Actions タブの該当の workflow に飛びます。
appveyor にも同様の機能があります。
https://www.appveyor.com/docs/status-badges/
https://srz-zumix.blogspot.com/2015/03/appveyor-c-ci.html
> AppVeyor でもバッジが付けられます。
> プロジェクトの SETTINGS に Badges があるので、そこでバッジの URL がわかります。
設定メニューから URL を取得できます。

CI の状態を確認できるように badge を追加する

---

.github/workflows/msbuild.yml

成果物のアップロード処理を分離
インストーラ (exe) とバイナリおよび pdb(zip) を別々の artifacts としてアップロードします。
インストーラだけほしいときに、すべてダウンロードするのは無駄なためです。

成果物のアップロード処理を分離

---

doc/en/html/about/history.html
doc/ja/html/about/history.html
teraterm/teraterm/buffer.c

- 5.2より前と同じ動作になった
- 2cellより大きな文字も考慮した

文字選択時、マウスポインタが文字の右側か左側かを考慮するよう修正 #468

---

doc/en/html/about/history.html
doc/ja/html/about/history.html
teraterm/ttpmacro/ttmacro.cpp

- 「ユーザーがログオンしているかどうかにかかわらず実行する」= ON 時
- メッセージポンプとアイドル処理を連続して実行できるようにした
- GetMessage()でブロックしないようにした

タスクスケジューラから実行できないことがあったので修正 #196

---

teraterm/common/comportinfo.cpp
teraterm/common/dlglib_tmpl.cpp
teraterm/common/history_store.cpp
teraterm/common/tipwin.cpp
teraterm/common/tmfc_propdlg.cpp
teraterm/ttpcmn/ttcmn_notify.cpp

- warning C4005: '_malloca': マクロが再定義されました。
- Debug時
- warning C4189: 'port_no': ローカル変数が初期化されましたが、参照されていません
- warning C4018: '>': signed と unsigned の数値を比較しようとしました。
変更履歴 不要
port 不要

コンパイラの警告対策

---

teraterm/ttpfile/bplus.h
teraterm/ttpfile/kermit.h
teraterm/ttpfile/quickvan.h
teraterm/ttpfile/xmodem.h
teraterm/ttpfile/ymodem.h
teraterm/ttpfile/zmodem.h

- コンパイラ警告対応
warning: 'struct FileVarProto' declared inside parameter list will not be visible outside of this definition or declaration
変更履歴 不要
PORT 不要

refactor ttpfile

---

teraterm/teraterm/vtwin.cpp

- ソースコードはShift_JIS、"能"の2byte目が"\"となる
- 次の行と連結してしまい、コメントアウトされる
- gccでビルドした場合処理発生
- 入力文字コード未指定時、UTF-8として処理される
- VSでも日本語環境以外で問題が起きるかも
変更履歴 不要
port 不要

行末に"能"を置かないよう修正

---

doc/en/html/setup/lng.html
doc/ja/html/setup/lng.html

- chmファイルで文字化けすることがあるため
- 各文字コードで表現できるよう修正
- PRいただいたlngファイルの説明にアカウントへのリンクを追加した
- en = iso-8859-1
- ja = Shift_JIS

lng.html の文字コードをUTF-8から元に戻した #589

---

teraterm/teraterm/vtwin.cpp

ディスプレイのDPI取得を誤っている場合がある #555 につきまして、
VTWinを最大化した状態でDPIに変化があった場合にフォントサイズがDPIに応じたサイズにならない不具合の修正パッチをお送りさせて頂きます。

ディスプレイのDPI取得を誤っている場合がある #555 (VTWin最大化時の不具合修正)

---

teraterm/teraterm/vtwin.cpp

VT window を最大化した場合に描画が崩れるため、行/列数の更新処理を元の処理に戻す修正になります。

ディスプレイのDPI取得を誤っている場合がある(VTWindow最大化時の描画崩れの修正) #555

---

cygwin/cygterm/cygterm.cpp
doc/en/html/about/history.html
doc/ja/html/about/history.html

#645 Cygterm+ の -o オプション指定時の処理誤りの修正パッチをお送りさせて頂きます。

Tera Term マクロで cygconnect を実行すると「/D=XXXXXXXX\n指定されたファイルがみつかりません。」と表示され、cygterm が起動しない。 #645

---

installer/teraterm.iss

この変更で、このようになる
- 前回、デフォルト言語（OSの言語）から変更していた場合 次のインストールでOSの言語になる（再度選び直す必要がある）
- 前回はOSの言語がサポートされておらず、英語でインストールした場合 新しいインストーラ―で新しくOSの言語が含まれるようになった場合、OSの言語がデフォルトになる

インストーラのメッセージ言語のデフォルトが、前回インストール時の言語ではなく自動になるようにした #636

---

doc/en/html/about/history.html
doc/ja/html/about/history.html
teraterm/teraterm/ttdde.c

Tera Term マクロの restoresetup で INIファイルを相対パスで指定した場合に、%APPDATA%\teraterm5 からの相対パスにならない #706

---

ttssh2/ttxssh/digest.h
ttssh2/ttxssh/mac.h

- 不完全構造体, 内部構造の隠蔽化のため使用
- 次のようなエラーや警告を回避
- warning: declaration of 'struct Mac' will not be visible outside of this function
- warning: 'struct Mac' declared inside parameter list will not be visible outside of this definition or declaration
- error: conflicting types for 'mac_init'; have 'int(struct Mac *)'
- Visual Studio 2022 17.14.9 ではエラーは出ないが、gcc,clangでもビルドできるよう修正

構造体を事前に宣言するようにした

---

installer/release/license.txt

インストーラー用ライセンスファイルへの TTXChangeFontSize の記載漏れの修正になります。

インストーラー用ライセンスファイルへの TTXChangeFontSize の記載漏れを修正 #599

---

teraterm/teraterm/filesys_proto.cpp
teraterm/teraterm/filesys_proto.h
teraterm/ttpfile/bplus.c
teraterm/ttpfile/kermit.c
teraterm/ttpfile/kermit.h
teraterm/ttpfile/quickvan.c
teraterm/ttpfile/quickvan.h
teraterm/ttpfile/ymodem.c
teraterm/ttpfile/ymodem.h

- 各プロトコル処理にキャンセルを通知した後、プロトコルごとの特別処理をなくした
- filesys_proto.cpp
- プロトコルごとの処理にコメントを追加した
- filesys_proto.h
- cancel()後、parse()でFALSEが返ってくるよう修正した
- ymodem
- kermitの送信、受信
- 取得,finishは未テスト
- BPlus, QuickVanはソースを見て修正、未テスト
- ymodem 受信時、キャンセルの受信に未対応と思われる

プロトコルのキャンセル処理の修正 #473

---

teraterm/common/directx.cpp

- DirectX が使えない環境の場合発生
- リリースバイナリはVisual Studio 2022でビルドしているので、Windows7以上で動作
- Windows7以上ではDirectXが使用可
- リリースバイナリでは発生しない不具合のはず
- DirectX の初期化を行っていないのに終了処理を行っていた

Tera Term終了時不正な処理が発生する場合があるので修正 #801

---

installer/release/.editorconfig
installer/release/lang_utf8/.editorconfig
teraterm/teraterm/font_pp.cpp
teraterm/teraterm/font_pp.rc

- フォントタブのコントロールが重ならないよう修正
- .editorconfig 修正
- 不要な.editorconfigを削除
- installer/release/lang_utf8/.editorconfig を修正
- 行末スペース削除など追加

ANSI API選択時、CodePageが無効になっていたので修正 #812

---

doc/en/html/menu/setup-additional-font.html
doc/ja/html/menu/setup-additional-font.html
teraterm/teraterm/font_pp.cpp

Unicode API時にCodePageが有効になる場合があったので修正 #812

---

doc/en/html/about/difference.html
doc/en/html/about/emulations_dec_special.html
doc/en/html/macro/command/connect.html
doc/en/html/macro/command/gettime.html
doc/en/html/macro/command/setfileattr.html
doc/en/html/menu/file-new.html
doc/en/html/menu/file.html
doc/en/html/reference/sourcecode.html
doc/en/html/setup/lng.html
doc/en/html/usage/tips/zmodem.html
doc/ja/html/about/difference.html
doc/ja/html/about/emulations_dec_special.html
doc/ja/html/macro/command/connect.html
doc/ja/html/macro/command/gettime.html
doc/ja/html/macro/command/setfileattr.html
doc/ja/html/menu/file-new.html
doc/ja/html/menu/file.html
doc/ja/html/reference/sourcecode.html
doc/ja/html/setup/lng.html
doc/ja/html/usage/tips/zmodem.html

マニュアルのリンク先を更新する修正です。
記載内容の変更は行っていないため、改版履歴への記載は不要です。

マニュアル(htmlファイル)のリンク先の更新 #857
