doc/en/html/reference/develop.html
doc/ja/html/reference/develop.html

まだ Subversion の記述が残っている部分があるのに気づいたので修正しました。

develop.html「Subversion をインストールします」から「Git for Windows」に変更

---

doc/en/html/about/history.html
doc/ja/html/about/history.html
ttssh2/ttxssh/kex.c
ttssh2/ttxssh/ssh.c
ttssh2/ttxssh/ttxssh.h

OpenSSHのstrice KEXに対応した。
Terrapin Attackへの対応。https://www.terrapin-attack.com

strict KEX対応

---

doc/en/html/about/history.html
doc/ja/html/about/history.html
ttssh2/ttxssh/kex.c
ttssh2/ttxssh/ssh.c
ttssh2/ttxssh/ttxssh.h

strict kex対応 (4-stable)

---

doc/en/html/about/history.html
doc/ja/html/about/history.html
teraterm/teraterm/ttdde.c

- xmodemsend と xmodemrecv の処理が入れ替わっていたので修正

xmodemsend, xmodemrecv - it doens't work #123

---

teraterm/teraterm/vtwin.cpp

do not create/destory TipWin when window is hidden

---

doc/en/html/about/history.html
doc/ja/html/about/history.html
teraterm/ttpmacro/ttl_gui.cpp

clipb2var が機能していなかったので修正

---

TTXKanjiMenu/ttxkanjimenu.c

- Hide title bar や Hide menu bar のとき
- メニューがポップアップメニューになる
- ポップアップメニューではメニューの項目を選択した直後メニューは破棄される
- メニュー項目のdwItemDataに入れたデータを利用していたが正しく読み込めなかった
- メニューが破棄されていても正しく動作するよう修正

漢字コードが正しく選択できない場合があったので修正 #265

---

installer/teraterm.iss
installer/teraterm_cmake.iss.in

インストーラの言語選択で選べるように追加しました。
スペイン語の末尾の不要な「:」を除去しました。

add support for tamil in installer

---

doc/en/html/about/history.html
doc/ja/html/about/history.html
teraterm/teraterm/vtwin.cpp

fix for #323

---

teraterm/teraterm/buffer.c

e91f4dcd53a31e8e94ca2f015b64f2db7d72c8bc の一部だけを戻すことで、以前と同等の動きになることがわかりました。

tweak X position to avoid sensitive selection

---

doc/en/html/setup/teraterm-ini.html
doc/ja/html/setup/teraterm-ini.html

「Tera Term 設定ファイルの全項目一覧」から YmodemLog の説明へのリンクを追加する修正を提案させて頂きます。

YmodemLog オプションのリンクを追加 #357

---

doc/en/html/usage/tips/xmodem.html
doc/en/html/usage/tips/zmodem.html

XMODEM と ZMODEM の英語版マニュアルに、日本語版マニュアルのログ取得のヒントの記載を反映する PR をお送りさせて頂きます。

XMODEM と ZMODEM のマニュアル修正(英語版に日本語版の記載を反映) #360

---

doc/en/html/menu/file-new.html
doc/ja/html/menu/file-new.html

- Disabling "Line at a time" mode へのリンク

New Connection ダイアログのドキュメントにリンクを追加 #387

---

doc/en/html/about/copyright.html
doc/ja/html/about/copyright.html

- ドキュメント内の参照を削除/変更
- Tera Term Pro(original) の URL は2.3へのリンクへ修正

hp.vector.co.jp サービス終了 #259

---

TTXKanjiMenu/ttxkanjimenu.c
installer/release/lang_utf8/English.lng
installer/release/lang_utf8/French.lng
installer/release/lang_utf8/German.lng
installer/release/lang_utf8/Japanese.lng
installer/release/lang_utf8/Korean.lng
installer/release/lang_utf8/Russian.lng
installer/release/lang_utf8/Simplified Chinese.lng
installer/release/lang_utf8/Spanish.lng
installer/release/lang_utf8/Tamil.lng
installer/release/lang_utf8/Traditional Chinese.lng

- 設定(Setting)変更
- &S -> &I
- &Shift_JIS と重複していた
- Ambiguous Character Width に追加
- &1, &2

アクセスキーを調整した #353

---

teraterm/teraterm/coding_pp.cpp

Override Emoji Charactor width のプルダウンが有効になることがあるので修正 #501

---

.github/workflows/msbuild.yml

手動で GitHub Actions の workflow を実行できるように workflow_dispatch トリガーを追加
https://qiita.com/chihiro/items/8b2918ceb709cb9079e8

手動で GitHub Actions の workflow を実行できるように workflow_dispatch トリガーを追加

---

.github/workflows/msbuild.yml

キャッシュキーを更新 (トリガー、バッチファイルのハッシュを含める)

キャッシュキーを更新 (トリガー、バッチファイルのハッシュを含める)

---

ttssh2/ttxssh/CMakeLists.txt

- cmakeビルド用
- 34d1d16e70fdc726f3c1ef34618b01b4ce8d1367

CMakeLists.txt にファイルを追加 #89

---

doc/en/html/about/history.html
doc/ja/html/about/history.html
teraterm/common/ttlib_static.c
teraterm/teraterm/vtwin.cpp
teraterm/teraterm/vtwin.h

ディスプレイのDPI取得を誤っている場合がある? #555 につきまして、不具合修正用の PR をお送りさせて頂きます。

ディスプレイのDPI取得を誤っている場合がある? #555

---

doc/en/html/about/ctrlseq.html
doc/en/html/about/history.html
doc/ja/html/about/ctrlseq.html
doc/ja/html/about/history.html
teraterm/common/tttypes.h
teraterm/teraterm/vtterm.c

5年前に追加されていたのを見逃していた。
https://invisible-island.net/xterm/xterm.log.html#xterm_360

SGR-Pixels形式の拡張マウストラッキングモードに対応した #575

---

teraterm/common/tmfc.h
teraterm/common/tmfc_frame.cpp
teraterm/teraterm/addsetting.h
teraterm/teraterm/vtwin.cpp

LPCTSTR を LPCWSTR へ変更

---

teraterm/teraterm/addsetting.h
teraterm/teraterm/vtwin.cpp

マウスカーソルのリソースIDをANSI版を使用するように修正

---

doc/en/html/about/history.html
doc/ja/html/about/history.html

- ユーザに関係ない部分を省略
- 保存されないことを追加
- 英語の修正

変更履歴を修正 #460

---

buildtools/install_cygwin.cmake

- ccc8ef91d3b814f29c29cd8657b526d4940416e8

updated cygwin setup to 2.934 #605

---

doc/en/html/about/history.html
doc/ja/html/about/history.html

改版履歴の issue へのリンクを (TTXChangeFontSize 側) に移動しました。

Feature Request: Change the font size using Ctrl + the mouse wheel #599

---

teraterm/teraterm/broadcast.cpp

TABを入力出来るようBroadcastダイアログの処理を元に戻す修正パッチをお送りさせて頂きます。

Broadcast command の realtime で一部キーでダイアログにフォーカスが取られる #644

---

doc/en/html/about/history.html
doc/ja/html/about/history.html
teraterm/teraterm/buffer.c

文字選択時、マウスポインタが文字の右側か左側かを考慮するよう修正 #468

---

.github/workflows/msbuild.yml

About ダイアログのビルド時刻が UTC になるので、tzutil で JST を設定する #679

About ダイアログのビルド時刻が UTC になるので、tzutil で JST を設定する #679

---

doc/en/html/about/history.html
doc/ja/html/about/history.html

変更履歴を修正 #653

---

installer/release/lang_utf8/es_ES.lng
installer/release/lang_utf8/fr_FR.lng
installer/release/lang_utf8/ko_KR.lng
installer/release/lang_utf8/ru_RU.lng
installer/release/lang_utf8/ta_IN.lng

言語ファイルの誤記の修正 #699

---

teraterm/common/tt-version.h

Fix/#610 5_4_1_RC2

---

doc/en/html/about/history.html
doc/ja/html/about/history.html

5.4.1 の変更履歴を stable_5_4 から移植

---

installer/release/lang_utf8/it_IT.lng
installer/teraterm.iss

@namaya
Please check and merge. 
Thanks.

Add Italian language

---

doc/en/html/about/history.html
doc/en/html/setup/lng.html
installer/makelang.bat
installer/message_en_US.isl
installer/message_it_IT.isl
installer/message_ja_JP.isl
installer/release/lang/CMakeLists.txt
installer/release/lang_utf8/tr_TR.lng
installer/teraterm.iss

I have translated the language file into the Turkish language on installer side of Teraterm.

Adds Turkish language support on installer

---

doc/en/html/about/history.html
doc/en/html/setup/lng.html
doc/ja/html/about/history.html
doc/ja/html/setup/lng.html
installer/makelang.bat
installer/message_en_US.isl
installer/message_it_IT.isl
installer/message_ja_JP.isl
installer/release/lang/CMakeLists.txt
installer/release/lang_utf8/tr_TR.lng
installer/teraterm.iss

Receive pr/#748 UI lang turkish

---

doc/en/html/about/history.html
doc/en/html/setup/teraterm-ini.html
doc/ja/html/about/history.html
doc/ja/html/setup/teraterm-ini.html
installer/release/TERATERM.INI
ttssh2/ttxssh/ssh.c
ttssh2/ttxssh/ssh.h
ttssh2/ttxssh/ttxssh.c
ttssh2/ttxssh/ttxssh.h

SSH チャネル数の上限を撤廃する修正パッチをお送りさせて頂きます。

SSH 同時接続チャネル数が足りない #694

---

doc/en/html/about/history.html
doc/ja/html/about/history.html
teraterm/ttpfile/filesys_win32.cpp
teraterm/ttpfile/kermit.c

- Tera Term 5.0 から
(cherry picked from commit 4272cea7dc2ea838e6cbd85bdee35d491cea6356)

Kermit - Get で ttermpor.exe がクラッシュする不具合修正 #785

---

installer/release/lang_utf16le/CMakeLists.txt

lang_utf16le の CMakeLists.txt にトルコ語を追加する #838

---

installer/release/IBMKEYB.CNF
installer/release/TERATERM.INI
installer/release/VT200.CNF

キーボード設定ファイルと TERATERM.INI の修正案をお送りさせて頂きます。

インストラーにTTXChangeFontSizeが含まれていない #828

---

doc/en/html/usage/change_fontsize.html
doc/ja/html/usage/change_fontsize.html

ヘルプファイルにTTXChangeFontSizeの説明を追加する #829
